### PR TITLE
Add Strong Name to Assembly

### PR DESCRIPTION
**Pull request by crazyht24**
Just little addition allow using assembly in StrongNamed project.

### CODE REVIEW

**Comment by PureKrome** [comment]
I'm going to take a really wild guess about this .... but ..

no

nono

and

frak no

This has [already been discussed previously by smarter ladies and gentlemen](https://github.com/octokit/octokit.net/issues/405).

just sayin'

**Comment by crazyht24** [comment]
StrongName have no impact. You can continue to use it in not sign project without modification, but you can use it in StrongNamed project.

**Comment by phillip-haydon** [comment]
*shiver* 

I don't know what to do. I don't want to have the main Nuget signed, rather just continue with it being non-signed.

Thinking I'll accept but if there's issues I'll roll it out and then release it as a separate nuget.

**Comment by PureKrome** [comment]
>I don't know what to do.

don't accept and don't promote signing. people can build their own. this puts further pressure on MS to maybe patch legacy stuff that require signing.

**Comment by phillip-haydon** [comment]
Copying @simoncropp if it doesn't mind.

@crazyht24 does this need to be signed, can you not ILMerge this into your assembly?

**Comment by SimonCropp** [comment]
So the validar ref lib has no dependency on simplevalidator https://github.com/Fody/Validar/blob/master/ReferenceAssembly/ReferenceAssembly.csproj

So i am indifferent.

Since simple validator is primarily used by top level apps, which can ilmerge, i dont think the need justfies the pain caused by SN

**Pull request closed without merging**
