### PR TITLE
Fix MaximumLength-Rule for null values

### PR DESCRIPTION
**Pull request by PeterVD-Lansweeper**

### CODE REVIEW

**Comment by phillip-haydon** [comment]
Awesomesauce!

**Comment by phillip-haydon** [comment]
:(

MaximumLengthTests

^ This test fails. Could you fix it please :D. App Veyor failed.

**Comment by PeterVD-Lansweeper** [comment]
Indeed. 😲
So the behavior was intentional after all. 😊

I modified the tests accordingly.

**Comment by phillip-haydon** [comment]
Thanks. I was prob tired when I wrote it. Your fix makes more sense than my silly code. 

I thought App Veyor was setup to post to Nuget but I guess I'm wrong. May need to upload it manually when I get home.

**Pull request merged**
